name: Test

on:
  push:
    branches:
      - "master"
      - "develop"
  pull_request:
    branches:
      - "develop"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.4'
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Go Generate
      run: go generate ./...

    - name: Run tests with coverage
      run: go test ./...

